/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.12
 * source: arike_fifo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./arike_utils";
import * as pb_1 from "google-protobuf";
export namespace arike_pb {
    export class FifoMeta extends pb_1.Message {
        #one_of_decls: number[][] = [[3]];
        constructor(data?: any[] | ({
            name?: string;
            val_type?: dependency_1.arike_pb.ValType;
        } & (({
            max_size?: number;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("val_type" in data && data.val_type != undefined) {
                    this.val_type = data.val_type;
                }
                if ("max_size" in data && data.max_size != undefined) {
                    this.max_size = data.max_size;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get val_type() {
            return pb_1.Message.getFieldWithDefault(this, 2, dependency_1.arike_pb.ValType.INT) as dependency_1.arike_pb.ValType;
        }
        set val_type(value: dependency_1.arike_pb.ValType) {
            pb_1.Message.setField(this, 2, value);
        }
        get max_size() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set max_size(value: number) {
            pb_1.Message.setOneofField(this, 3, this.#one_of_decls[0], value);
        }
        get has_max_size() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get _max_size() {
            const cases: {
                [index: number]: "none" | "max_size";
            } = {
                0: "none",
                3: "max_size"
            };
            return cases[pb_1.Message.computeOneofCase(this, [3])];
        }
        static fromObject(data: {
            name?: string;
            val_type?: dependency_1.arike_pb.ValType;
            max_size?: number;
        }): FifoMeta {
            const message = new FifoMeta({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.val_type != null) {
                message.val_type = data.val_type;
            }
            if (data.max_size != null) {
                message.max_size = data.max_size;
            }
            return message;
        }
        toObject() {
            const data: {
                name?: string;
                val_type?: dependency_1.arike_pb.ValType;
                max_size?: number;
            } = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.val_type != null) {
                data.val_type = this.val_type;
            }
            if (this.max_size != null) {
                data.max_size = this.max_size;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.val_type != dependency_1.arike_pb.ValType.INT)
                writer.writeEnum(2, this.val_type);
            if (this.has_max_size)
                writer.writeUint64(3, this.max_size);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FifoMeta {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FifoMeta();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.val_type = reader.readEnum();
                        break;
                    case 3:
                        message.max_size = reader.readUint64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FifoMeta {
            return FifoMeta.deserialize(bytes);
        }
    }
    export class FifoNamesCount extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            name?: string;
            n?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("n" in data && data.n != undefined) {
                    this.n = data.n;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get n() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set n(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            name?: string;
            n?: number;
        }): FifoNamesCount {
            const message = new FifoNamesCount({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.n != null) {
                message.n = data.n;
            }
            return message;
        }
        toObject() {
            const data: {
                name?: string;
                n?: number;
            } = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.n != null) {
                data.n = this.n;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.n != 0)
                writer.writeUint32(2, this.n);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FifoNamesCount {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FifoNamesCount();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.n = reader.readUint32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FifoNamesCount {
            return FifoNamesCount.deserialize(bytes);
        }
    }
    export class FifoValue extends pb_1.Message {
        #one_of_decls: number[][] = [[2]];
        constructor(data?: any[] | ({
            name?: string;
            int_value?: number[];
            float_value?: number[];
            str_value?: string[];
            bool_value?: boolean[];
        } & (({
            val_type?: dependency_1.arike_pb.ValType;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3, 4, 5, 6], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("val_type" in data && data.val_type != undefined) {
                    this.val_type = data.val_type;
                }
                if ("int_value" in data && data.int_value != undefined) {
                    this.int_value = data.int_value;
                }
                if ("float_value" in data && data.float_value != undefined) {
                    this.float_value = data.float_value;
                }
                if ("str_value" in data && data.str_value != undefined) {
                    this.str_value = data.str_value;
                }
                if ("bool_value" in data && data.bool_value != undefined) {
                    this.bool_value = data.bool_value;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get val_type() {
            return pb_1.Message.getFieldWithDefault(this, 2, dependency_1.arike_pb.ValType.INT) as dependency_1.arike_pb.ValType;
        }
        set val_type(value: dependency_1.arike_pb.ValType) {
            pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
        }
        get has_val_type() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get int_value() {
            return pb_1.Message.getFieldWithDefault(this, 3, []) as number[];
        }
        set int_value(value: number[]) {
            pb_1.Message.setField(this, 3, value);
        }
        get float_value() {
            return pb_1.Message.getFieldWithDefault(this, 4, []) as number[];
        }
        set float_value(value: number[]) {
            pb_1.Message.setField(this, 4, value);
        }
        get str_value() {
            return pb_1.Message.getFieldWithDefault(this, 5, []) as string[];
        }
        set str_value(value: string[]) {
            pb_1.Message.setField(this, 5, value);
        }
        get bool_value() {
            return pb_1.Message.getFieldWithDefault(this, 6, []) as boolean[];
        }
        set bool_value(value: boolean[]) {
            pb_1.Message.setField(this, 6, value);
        }
        get _val_type() {
            const cases: {
                [index: number]: "none" | "val_type";
            } = {
                0: "none",
                2: "val_type"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2])];
        }
        static fromObject(data: {
            name?: string;
            val_type?: dependency_1.arike_pb.ValType;
            int_value?: number[];
            float_value?: number[];
            str_value?: string[];
            bool_value?: boolean[];
        }): FifoValue {
            const message = new FifoValue({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.val_type != null) {
                message.val_type = data.val_type;
            }
            if (data.int_value != null) {
                message.int_value = data.int_value;
            }
            if (data.float_value != null) {
                message.float_value = data.float_value;
            }
            if (data.str_value != null) {
                message.str_value = data.str_value;
            }
            if (data.bool_value != null) {
                message.bool_value = data.bool_value;
            }
            return message;
        }
        toObject() {
            const data: {
                name?: string;
                val_type?: dependency_1.arike_pb.ValType;
                int_value?: number[];
                float_value?: number[];
                str_value?: string[];
                bool_value?: boolean[];
            } = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.val_type != null) {
                data.val_type = this.val_type;
            }
            if (this.int_value != null) {
                data.int_value = this.int_value;
            }
            if (this.float_value != null) {
                data.float_value = this.float_value;
            }
            if (this.str_value != null) {
                data.str_value = this.str_value;
            }
            if (this.bool_value != null) {
                data.bool_value = this.bool_value;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.has_val_type)
                writer.writeEnum(2, this.val_type);
            if (this.int_value.length)
                writer.writePackedInt64(3, this.int_value);
            if (this.float_value.length)
                writer.writePackedDouble(4, this.float_value);
            if (this.str_value.length)
                writer.writeRepeatedString(5, this.str_value);
            if (this.bool_value.length)
                writer.writePackedBool(6, this.bool_value);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FifoValue {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new FifoValue();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.val_type = reader.readEnum();
                        break;
                    case 3:
                        message.int_value = reader.readPackedInt64();
                        break;
                    case 4:
                        message.float_value = reader.readPackedDouble();
                        break;
                    case 5:
                        pb_1.Message.addToRepeatedField(message, 5, reader.readString());
                        break;
                    case 6:
                        message.bool_value = reader.readPackedBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): FifoValue {
            return FifoValue.deserialize(bytes);
        }
    }
    export class CreateFifosRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            collection?: string;
            fifos?: FifoMeta[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("collection" in data && data.collection != undefined) {
                    this.collection = data.collection;
                }
                if ("fifos" in data && data.fifos != undefined) {
                    this.fifos = data.fifos;
                }
            }
        }
        get collection() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set collection(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get fifos() {
            return pb_1.Message.getRepeatedWrapperField(this, FifoMeta, 2) as FifoMeta[];
        }
        set fifos(value: FifoMeta[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            collection?: string;
            fifos?: ReturnType<typeof FifoMeta.prototype.toObject>[];
        }): CreateFifosRequest {
            const message = new CreateFifosRequest({});
            if (data.collection != null) {
                message.collection = data.collection;
            }
            if (data.fifos != null) {
                message.fifos = data.fifos.map(item => FifoMeta.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                collection?: string;
                fifos?: ReturnType<typeof FifoMeta.prototype.toObject>[];
            } = {};
            if (this.collection != null) {
                data.collection = this.collection;
            }
            if (this.fifos != null) {
                data.fifos = this.fifos.map((item: FifoMeta) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.collection.length)
                writer.writeString(1, this.collection);
            if (this.fifos.length)
                writer.writeRepeatedMessage(2, this.fifos, (item: FifoMeta) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateFifosRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CreateFifosRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.collection = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message.fifos, () => pb_1.Message.addToRepeatedWrapperField(message, 2, FifoMeta.deserialize(reader), FifoMeta));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CreateFifosRequest {
            return CreateFifosRequest.deserialize(bytes);
        }
    }
    export class CreateFifosResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            status?: dependency_1.arike_pb.StatusCode;
            already_exists?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("already_exists" in data && data.already_exists != undefined) {
                    this.already_exists = data.already_exists;
                }
            }
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 1, dependency_1.arike_pb.StatusCode.OK) as dependency_1.arike_pb.StatusCode;
        }
        set status(value: dependency_1.arike_pb.StatusCode) {
            pb_1.Message.setField(this, 1, value);
        }
        get already_exists() {
            return pb_1.Message.getFieldWithDefault(this, 2, []) as string[];
        }
        set already_exists(value: string[]) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            status?: dependency_1.arike_pb.StatusCode;
            already_exists?: string[];
        }): CreateFifosResponse {
            const message = new CreateFifosResponse({});
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.already_exists != null) {
                message.already_exists = data.already_exists;
            }
            return message;
        }
        toObject() {
            const data: {
                status?: dependency_1.arike_pb.StatusCode;
                already_exists?: string[];
            } = {};
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.already_exists != null) {
                data.already_exists = this.already_exists;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.status != dependency_1.arike_pb.StatusCode.OK)
                writer.writeEnum(1, this.status);
            if (this.already_exists.length)
                writer.writeRepeatedString(2, this.already_exists);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateFifosResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CreateFifosResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.status = reader.readEnum();
                        break;
                    case 2:
                        pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CreateFifosResponse {
            return CreateFifosResponse.deserialize(bytes);
        }
    }
    export class DeleteFifosRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            collection?: string;
            names?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("collection" in data && data.collection != undefined) {
                    this.collection = data.collection;
                }
                if ("names" in data && data.names != undefined) {
                    this.names = data.names;
                }
            }
        }
        get collection() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set collection(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get names() {
            return pb_1.Message.getFieldWithDefault(this, 2, []) as string[];
        }
        set names(value: string[]) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            collection?: string;
            names?: string[];
        }): DeleteFifosRequest {
            const message = new DeleteFifosRequest({});
            if (data.collection != null) {
                message.collection = data.collection;
            }
            if (data.names != null) {
                message.names = data.names;
            }
            return message;
        }
        toObject() {
            const data: {
                collection?: string;
                names?: string[];
            } = {};
            if (this.collection != null) {
                data.collection = this.collection;
            }
            if (this.names != null) {
                data.names = this.names;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.collection.length)
                writer.writeString(1, this.collection);
            if (this.names.length)
                writer.writeRepeatedString(2, this.names);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteFifosRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteFifosRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.collection = reader.readString();
                        break;
                    case 2:
                        pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DeleteFifosRequest {
            return DeleteFifosRequest.deserialize(bytes);
        }
    }
    export class DeleteFifosResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            status?: dependency_1.arike_pb.StatusCode;
            not_found?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("not_found" in data && data.not_found != undefined) {
                    this.not_found = data.not_found;
                }
            }
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 1, dependency_1.arike_pb.StatusCode.OK) as dependency_1.arike_pb.StatusCode;
        }
        set status(value: dependency_1.arike_pb.StatusCode) {
            pb_1.Message.setField(this, 1, value);
        }
        get not_found() {
            return pb_1.Message.getFieldWithDefault(this, 2, []) as string[];
        }
        set not_found(value: string[]) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            status?: dependency_1.arike_pb.StatusCode;
            not_found?: string[];
        }): DeleteFifosResponse {
            const message = new DeleteFifosResponse({});
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.not_found != null) {
                message.not_found = data.not_found;
            }
            return message;
        }
        toObject() {
            const data: {
                status?: dependency_1.arike_pb.StatusCode;
                not_found?: string[];
            } = {};
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.not_found != null) {
                data.not_found = this.not_found;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.status != dependency_1.arike_pb.StatusCode.OK)
                writer.writeEnum(1, this.status);
            if (this.not_found.length)
                writer.writeRepeatedString(2, this.not_found);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteFifosResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteFifosResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.status = reader.readEnum();
                        break;
                    case 2:
                        pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DeleteFifosResponse {
            return DeleteFifosResponse.deserialize(bytes);
        }
    }
    export class ListFifosRequest extends pb_1.Message {
        #one_of_decls: number[][] = [[2]];
        constructor(data?: any[] | ({
            collection?: string;
        } & (({
            pattern?: string;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("collection" in data && data.collection != undefined) {
                    this.collection = data.collection;
                }
                if ("pattern" in data && data.pattern != undefined) {
                    this.pattern = data.pattern;
                }
            }
        }
        get collection() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set collection(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get pattern() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set pattern(value: string) {
            pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
        }
        get has_pattern() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get _pattern() {
            const cases: {
                [index: number]: "none" | "pattern";
            } = {
                0: "none",
                2: "pattern"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2])];
        }
        static fromObject(data: {
            collection?: string;
            pattern?: string;
        }): ListFifosRequest {
            const message = new ListFifosRequest({});
            if (data.collection != null) {
                message.collection = data.collection;
            }
            if (data.pattern != null) {
                message.pattern = data.pattern;
            }
            return message;
        }
        toObject() {
            const data: {
                collection?: string;
                pattern?: string;
            } = {};
            if (this.collection != null) {
                data.collection = this.collection;
            }
            if (this.pattern != null) {
                data.pattern = this.pattern;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.collection.length)
                writer.writeString(1, this.collection);
            if (this.has_pattern)
                writer.writeString(2, this.pattern);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ListFifosRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ListFifosRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.collection = reader.readString();
                        break;
                    case 2:
                        message.pattern = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ListFifosRequest {
            return ListFifosRequest.deserialize(bytes);
        }
    }
    export class ListFifosResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            status?: dependency_1.arike_pb.StatusCode;
            fifos?: FifoMeta[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("fifos" in data && data.fifos != undefined) {
                    this.fifos = data.fifos;
                }
            }
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 1, dependency_1.arike_pb.StatusCode.OK) as dependency_1.arike_pb.StatusCode;
        }
        set status(value: dependency_1.arike_pb.StatusCode) {
            pb_1.Message.setField(this, 1, value);
        }
        get fifos() {
            return pb_1.Message.getRepeatedWrapperField(this, FifoMeta, 2) as FifoMeta[];
        }
        set fifos(value: FifoMeta[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            status?: dependency_1.arike_pb.StatusCode;
            fifos?: ReturnType<typeof FifoMeta.prototype.toObject>[];
        }): ListFifosResponse {
            const message = new ListFifosResponse({});
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.fifos != null) {
                message.fifos = data.fifos.map(item => FifoMeta.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                status?: dependency_1.arike_pb.StatusCode;
                fifos?: ReturnType<typeof FifoMeta.prototype.toObject>[];
            } = {};
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.fifos != null) {
                data.fifos = this.fifos.map((item: FifoMeta) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.status != dependency_1.arike_pb.StatusCode.OK)
                writer.writeEnum(1, this.status);
            if (this.fifos.length)
                writer.writeRepeatedMessage(2, this.fifos, (item: FifoMeta) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ListFifosResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ListFifosResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.status = reader.readEnum();
                        break;
                    case 2:
                        reader.readMessage(message.fifos, () => pb_1.Message.addToRepeatedWrapperField(message, 2, FifoMeta.deserialize(reader), FifoMeta));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ListFifosResponse {
            return ListFifosResponse.deserialize(bytes);
        }
    }
    export class PushFifosRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            collection?: string;
            values?: FifoValue[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("collection" in data && data.collection != undefined) {
                    this.collection = data.collection;
                }
                if ("values" in data && data.values != undefined) {
                    this.values = data.values;
                }
            }
        }
        get collection() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set collection(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get values() {
            return pb_1.Message.getRepeatedWrapperField(this, FifoValue, 2) as FifoValue[];
        }
        set values(value: FifoValue[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            collection?: string;
            values?: ReturnType<typeof FifoValue.prototype.toObject>[];
        }): PushFifosRequest {
            const message = new PushFifosRequest({});
            if (data.collection != null) {
                message.collection = data.collection;
            }
            if (data.values != null) {
                message.values = data.values.map(item => FifoValue.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                collection?: string;
                values?: ReturnType<typeof FifoValue.prototype.toObject>[];
            } = {};
            if (this.collection != null) {
                data.collection = this.collection;
            }
            if (this.values != null) {
                data.values = this.values.map((item: FifoValue) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.collection.length)
                writer.writeString(1, this.collection);
            if (this.values.length)
                writer.writeRepeatedMessage(2, this.values, (item: FifoValue) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PushFifosRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PushFifosRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.collection = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message.values, () => pb_1.Message.addToRepeatedWrapperField(message, 2, FifoValue.deserialize(reader), FifoValue));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PushFifosRequest {
            return PushFifosRequest.deserialize(bytes);
        }
    }
    export class PushFifosResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            status?: dependency_1.arike_pb.StatusCode;
            not_found?: string[];
            invalid_type?: string[];
            non_inserted?: number[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2, 3, 4], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("not_found" in data && data.not_found != undefined) {
                    this.not_found = data.not_found;
                }
                if ("invalid_type" in data && data.invalid_type != undefined) {
                    this.invalid_type = data.invalid_type;
                }
                if ("non_inserted" in data && data.non_inserted != undefined) {
                    this.non_inserted = data.non_inserted;
                }
            }
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 1, dependency_1.arike_pb.StatusCode.OK) as dependency_1.arike_pb.StatusCode;
        }
        set status(value: dependency_1.arike_pb.StatusCode) {
            pb_1.Message.setField(this, 1, value);
        }
        get not_found() {
            return pb_1.Message.getFieldWithDefault(this, 2, []) as string[];
        }
        set not_found(value: string[]) {
            pb_1.Message.setField(this, 2, value);
        }
        get invalid_type() {
            return pb_1.Message.getFieldWithDefault(this, 3, []) as string[];
        }
        set invalid_type(value: string[]) {
            pb_1.Message.setField(this, 3, value);
        }
        get non_inserted() {
            return pb_1.Message.getFieldWithDefault(this, 4, []) as number[];
        }
        set non_inserted(value: number[]) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            status?: dependency_1.arike_pb.StatusCode;
            not_found?: string[];
            invalid_type?: string[];
            non_inserted?: number[];
        }): PushFifosResponse {
            const message = new PushFifosResponse({});
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.not_found != null) {
                message.not_found = data.not_found;
            }
            if (data.invalid_type != null) {
                message.invalid_type = data.invalid_type;
            }
            if (data.non_inserted != null) {
                message.non_inserted = data.non_inserted;
            }
            return message;
        }
        toObject() {
            const data: {
                status?: dependency_1.arike_pb.StatusCode;
                not_found?: string[];
                invalid_type?: string[];
                non_inserted?: number[];
            } = {};
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.not_found != null) {
                data.not_found = this.not_found;
            }
            if (this.invalid_type != null) {
                data.invalid_type = this.invalid_type;
            }
            if (this.non_inserted != null) {
                data.non_inserted = this.non_inserted;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.status != dependency_1.arike_pb.StatusCode.OK)
                writer.writeEnum(1, this.status);
            if (this.not_found.length)
                writer.writeRepeatedString(2, this.not_found);
            if (this.invalid_type.length)
                writer.writeRepeatedString(3, this.invalid_type);
            if (this.non_inserted.length)
                writer.writePackedUint64(4, this.non_inserted);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PushFifosResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PushFifosResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.status = reader.readEnum();
                        break;
                    case 2:
                        pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                        break;
                    case 3:
                        pb_1.Message.addToRepeatedField(message, 3, reader.readString());
                        break;
                    case 4:
                        message.non_inserted = reader.readPackedUint64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PushFifosResponse {
            return PushFifosResponse.deserialize(bytes);
        }
    }
    export class PullFifosRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            collection?: string;
            names_counts?: FifoNamesCount[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("collection" in data && data.collection != undefined) {
                    this.collection = data.collection;
                }
                if ("names_counts" in data && data.names_counts != undefined) {
                    this.names_counts = data.names_counts;
                }
            }
        }
        get collection() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set collection(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get names_counts() {
            return pb_1.Message.getRepeatedWrapperField(this, FifoNamesCount, 2) as FifoNamesCount[];
        }
        set names_counts(value: FifoNamesCount[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            collection?: string;
            names_counts?: ReturnType<typeof FifoNamesCount.prototype.toObject>[];
        }): PullFifosRequest {
            const message = new PullFifosRequest({});
            if (data.collection != null) {
                message.collection = data.collection;
            }
            if (data.names_counts != null) {
                message.names_counts = data.names_counts.map(item => FifoNamesCount.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                collection?: string;
                names_counts?: ReturnType<typeof FifoNamesCount.prototype.toObject>[];
            } = {};
            if (this.collection != null) {
                data.collection = this.collection;
            }
            if (this.names_counts != null) {
                data.names_counts = this.names_counts.map((item: FifoNamesCount) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.collection.length)
                writer.writeString(1, this.collection);
            if (this.names_counts.length)
                writer.writeRepeatedMessage(2, this.names_counts, (item: FifoNamesCount) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PullFifosRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PullFifosRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.collection = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message.names_counts, () => pb_1.Message.addToRepeatedWrapperField(message, 2, FifoNamesCount.deserialize(reader), FifoNamesCount));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PullFifosRequest {
            return PullFifosRequest.deserialize(bytes);
        }
    }
    export class PullFifosResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            status?: dependency_1.arike_pb.StatusCode;
            values?: FifoValue[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("values" in data && data.values != undefined) {
                    this.values = data.values;
                }
            }
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 1, dependency_1.arike_pb.StatusCode.OK) as dependency_1.arike_pb.StatusCode;
        }
        set status(value: dependency_1.arike_pb.StatusCode) {
            pb_1.Message.setField(this, 1, value);
        }
        get values() {
            return pb_1.Message.getRepeatedWrapperField(this, FifoValue, 2) as FifoValue[];
        }
        set values(value: FifoValue[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            status?: dependency_1.arike_pb.StatusCode;
            values?: ReturnType<typeof FifoValue.prototype.toObject>[];
        }): PullFifosResponse {
            const message = new PullFifosResponse({});
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.values != null) {
                message.values = data.values.map(item => FifoValue.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                status?: dependency_1.arike_pb.StatusCode;
                values?: ReturnType<typeof FifoValue.prototype.toObject>[];
            } = {};
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.values != null) {
                data.values = this.values.map((item: FifoValue) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.status != dependency_1.arike_pb.StatusCode.OK)
                writer.writeEnum(1, this.status);
            if (this.values.length)
                writer.writeRepeatedMessage(2, this.values, (item: FifoValue) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PullFifosResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PullFifosResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.status = reader.readEnum();
                        break;
                    case 2:
                        reader.readMessage(message.values, () => pb_1.Message.addToRepeatedWrapperField(message, 2, FifoValue.deserialize(reader), FifoValue));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PullFifosResponse {
            return PullFifosResponse.deserialize(bytes);
        }
    }
}
