/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.12
 * source: arike_main.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./arike_auth";
import * as dependency_2 from "./arike_collection";
import * as dependency_3 from "./arike_ts_variable";
import * as dependency_4 from "./arike_stack";
import * as dependency_5 from "./arike_fifo";
import * as dependency_6 from "./arike_sorted_list";
import * as grpc_1 from "@grpc/grpc-js";
export namespace arike_pb {
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedArikedbRPCService {
        static definition = {
            CreateCollections: {
                path: "/arike_pb.ArikedbRPC/CreateCollections",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.arike_pb.CreateCollectionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.arike_pb.CreateCollectionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_2.arike_pb.CreateCollectionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_2.arike_pb.CreateCollectionsResponse.deserialize(new Uint8Array(bytes))
            },
            DeleteCollections: {
                path: "/arike_pb.ArikedbRPC/DeleteCollections",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.arike_pb.DeleteCollectionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.arike_pb.DeleteCollectionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_2.arike_pb.DeleteCollectionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_2.arike_pb.DeleteCollectionsResponse.deserialize(new Uint8Array(bytes))
            },
            ListCollections: {
                path: "/arike_pb.ArikedbRPC/ListCollections",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.arike_pb.ListCollectionsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.arike_pb.ListCollectionsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_2.arike_pb.ListCollectionsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_2.arike_pb.ListCollectionsResponse.deserialize(new Uint8Array(bytes))
            },
            CreateVariables: {
                path: "/arike_pb.ArikedbRPC/CreateVariables",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_3.arike_pb.CreateVariablesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_3.arike_pb.CreateVariablesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_3.arike_pb.CreateVariablesResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_3.arike_pb.CreateVariablesResponse.deserialize(new Uint8Array(bytes))
            },
            DeleteVariables: {
                path: "/arike_pb.ArikedbRPC/DeleteVariables",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_3.arike_pb.DeleteVariablesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_3.arike_pb.DeleteVariablesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_3.arike_pb.DeleteVariablesResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_3.arike_pb.DeleteVariablesResponse.deserialize(new Uint8Array(bytes))
            },
            ListVariables: {
                path: "/arike_pb.ArikedbRPC/ListVariables",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_3.arike_pb.ListVariablesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_3.arike_pb.ListVariablesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_3.arike_pb.ListVariablesResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_3.arike_pb.ListVariablesResponse.deserialize(new Uint8Array(bytes))
            },
            SetVariables: {
                path: "/arike_pb.ArikedbRPC/SetVariables",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_3.arike_pb.SetVariablesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_3.arike_pb.SetVariablesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_3.arike_pb.SetVariablesResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_3.arike_pb.SetVariablesResponse.deserialize(new Uint8Array(bytes))
            },
            GetVariables: {
                path: "/arike_pb.ArikedbRPC/GetVariables",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_3.arike_pb.GetVariablesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_3.arike_pb.GetVariablesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_3.arike_pb.GetVariablesResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_3.arike_pb.GetVariablesResponse.deserialize(new Uint8Array(bytes))
            },
            SubscribeVariables: {
                path: "/arike_pb.ArikedbRPC/SubscribeVariables",
                requestStream: false,
                responseStream: true,
                requestSerialize: (message: dependency_3.arike_pb.SubscribeVariablesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_3.arike_pb.SubscribeVariablesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_3.arike_pb.TsVarValue) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_3.arike_pb.TsVarValue.deserialize(new Uint8Array(bytes))
            },
            CreateStacks: {
                path: "/arike_pb.ArikedbRPC/CreateStacks",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_4.arike_pb.CreateStacksRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_4.arike_pb.CreateStacksRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_4.arike_pb.CreateStacksResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_4.arike_pb.CreateStacksResponse.deserialize(new Uint8Array(bytes))
            },
            DeleteStacks: {
                path: "/arike_pb.ArikedbRPC/DeleteStacks",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_4.arike_pb.DeleteStacksRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_4.arike_pb.DeleteStacksRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_4.arike_pb.DeleteStacksResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_4.arike_pb.DeleteStacksResponse.deserialize(new Uint8Array(bytes))
            },
            ListStacks: {
                path: "/arike_pb.ArikedbRPC/ListStacks",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_4.arike_pb.ListStacksRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_4.arike_pb.ListStacksRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_4.arike_pb.ListStacksResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_4.arike_pb.ListStacksResponse.deserialize(new Uint8Array(bytes))
            },
            PutStacks: {
                path: "/arike_pb.ArikedbRPC/PutStacks",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_4.arike_pb.PutStacksRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_4.arike_pb.PutStacksRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_4.arike_pb.PutStacksResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_4.arike_pb.PutStacksResponse.deserialize(new Uint8Array(bytes))
            },
            PopStacks: {
                path: "/arike_pb.ArikedbRPC/PopStacks",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_4.arike_pb.PopStacksRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_4.arike_pb.PopStacksRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_4.arike_pb.PopStacksResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_4.arike_pb.PopStacksResponse.deserialize(new Uint8Array(bytes))
            },
            CreateFifos: {
                path: "/arike_pb.ArikedbRPC/CreateFifos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_5.arike_pb.CreateFifosRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_5.arike_pb.CreateFifosRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_5.arike_pb.CreateFifosResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_5.arike_pb.CreateFifosResponse.deserialize(new Uint8Array(bytes))
            },
            DeleteFifos: {
                path: "/arike_pb.ArikedbRPC/DeleteFifos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_5.arike_pb.DeleteFifosRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_5.arike_pb.DeleteFifosRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_5.arike_pb.DeleteFifosResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_5.arike_pb.DeleteFifosResponse.deserialize(new Uint8Array(bytes))
            },
            ListFifos: {
                path: "/arike_pb.ArikedbRPC/ListFifos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_5.arike_pb.ListFifosRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_5.arike_pb.ListFifosRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_5.arike_pb.ListFifosResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_5.arike_pb.ListFifosResponse.deserialize(new Uint8Array(bytes))
            },
            PushFifos: {
                path: "/arike_pb.ArikedbRPC/PushFifos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_5.arike_pb.PushFifosRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_5.arike_pb.PushFifosRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_5.arike_pb.PushFifosResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_5.arike_pb.PushFifosResponse.deserialize(new Uint8Array(bytes))
            },
            PullFifos: {
                path: "/arike_pb.ArikedbRPC/PullFifos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_5.arike_pb.PullFifosRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_5.arike_pb.PullFifosRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_5.arike_pb.PullFifosResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_5.arike_pb.PullFifosResponse.deserialize(new Uint8Array(bytes))
            },
            CreateSortedLists: {
                path: "/arike_pb.ArikedbRPC/CreateSortedLists",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_6.arike_pb.CreateSortedListsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_6.arike_pb.CreateSortedListsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_6.arike_pb.CreateSortedListsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_6.arike_pb.CreateSortedListsResponse.deserialize(new Uint8Array(bytes))
            },
            DeleteSortedLists: {
                path: "/arike_pb.ArikedbRPC/DeleteSortedLists",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_6.arike_pb.DeleteSortedListsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_6.arike_pb.DeleteSortedListsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_6.arike_pb.DeleteSortedListsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_6.arike_pb.DeleteSortedListsResponse.deserialize(new Uint8Array(bytes))
            },
            ListSortedLists: {
                path: "/arike_pb.ArikedbRPC/ListSortedLists",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_6.arike_pb.ListSortedListsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_6.arike_pb.ListSortedListsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_6.arike_pb.ListSortedListsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_6.arike_pb.ListSortedListsResponse.deserialize(new Uint8Array(bytes))
            },
            InsertSortedLists: {
                path: "/arike_pb.ArikedbRPC/InsertSortedLists",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_6.arike_pb.InsertSortedListsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_6.arike_pb.InsertSortedListsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_6.arike_pb.InsertSortedListsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_6.arike_pb.InsertSortedListsResponse.deserialize(new Uint8Array(bytes))
            },
            BiggestSortedLists: {
                path: "/arike_pb.ArikedbRPC/BiggestSortedLists",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_6.arike_pb.BiggestSortedListsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_6.arike_pb.BiggestSortedListsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_6.arike_pb.BiggestSortedListsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_6.arike_pb.BiggestSortedListsResponse.deserialize(new Uint8Array(bytes))
            },
            SmallestSortedLists: {
                path: "/arike_pb.ArikedbRPC/SmallestSortedLists",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_6.arike_pb.SmallestSortedListsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_6.arike_pb.SmallestSortedListsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_6.arike_pb.SmallestSortedListsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_6.arike_pb.SmallestSortedListsResponse.deserialize(new Uint8Array(bytes))
            },
            Authenticate: {
                path: "/arike_pb.ArikedbRPC/Authenticate",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.arike_pb.AuthenticateRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.arike_pb.AuthenticateRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.arike_pb.AuthenticateResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.arike_pb.AuthenticateResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract CreateCollections(call: grpc_1.ServerUnaryCall<dependency_2.arike_pb.CreateCollectionsRequest, dependency_2.arike_pb.CreateCollectionsResponse>, callback: grpc_1.sendUnaryData<dependency_2.arike_pb.CreateCollectionsResponse>): void;
        abstract DeleteCollections(call: grpc_1.ServerUnaryCall<dependency_2.arike_pb.DeleteCollectionsRequest, dependency_2.arike_pb.DeleteCollectionsResponse>, callback: grpc_1.sendUnaryData<dependency_2.arike_pb.DeleteCollectionsResponse>): void;
        abstract ListCollections(call: grpc_1.ServerUnaryCall<dependency_2.arike_pb.ListCollectionsRequest, dependency_2.arike_pb.ListCollectionsResponse>, callback: grpc_1.sendUnaryData<dependency_2.arike_pb.ListCollectionsResponse>): void;
        abstract CreateVariables(call: grpc_1.ServerUnaryCall<dependency_3.arike_pb.CreateVariablesRequest, dependency_3.arike_pb.CreateVariablesResponse>, callback: grpc_1.sendUnaryData<dependency_3.arike_pb.CreateVariablesResponse>): void;
        abstract DeleteVariables(call: grpc_1.ServerUnaryCall<dependency_3.arike_pb.DeleteVariablesRequest, dependency_3.arike_pb.DeleteVariablesResponse>, callback: grpc_1.sendUnaryData<dependency_3.arike_pb.DeleteVariablesResponse>): void;
        abstract ListVariables(call: grpc_1.ServerUnaryCall<dependency_3.arike_pb.ListVariablesRequest, dependency_3.arike_pb.ListVariablesResponse>, callback: grpc_1.sendUnaryData<dependency_3.arike_pb.ListVariablesResponse>): void;
        abstract SetVariables(call: grpc_1.ServerUnaryCall<dependency_3.arike_pb.SetVariablesRequest, dependency_3.arike_pb.SetVariablesResponse>, callback: grpc_1.sendUnaryData<dependency_3.arike_pb.SetVariablesResponse>): void;
        abstract GetVariables(call: grpc_1.ServerUnaryCall<dependency_3.arike_pb.GetVariablesRequest, dependency_3.arike_pb.GetVariablesResponse>, callback: grpc_1.sendUnaryData<dependency_3.arike_pb.GetVariablesResponse>): void;
        abstract SubscribeVariables(call: grpc_1.ServerWritableStream<dependency_3.arike_pb.SubscribeVariablesRequest, dependency_3.arike_pb.TsVarValue>): void;
        abstract CreateStacks(call: grpc_1.ServerUnaryCall<dependency_4.arike_pb.CreateStacksRequest, dependency_4.arike_pb.CreateStacksResponse>, callback: grpc_1.sendUnaryData<dependency_4.arike_pb.CreateStacksResponse>): void;
        abstract DeleteStacks(call: grpc_1.ServerUnaryCall<dependency_4.arike_pb.DeleteStacksRequest, dependency_4.arike_pb.DeleteStacksResponse>, callback: grpc_1.sendUnaryData<dependency_4.arike_pb.DeleteStacksResponse>): void;
        abstract ListStacks(call: grpc_1.ServerUnaryCall<dependency_4.arike_pb.ListStacksRequest, dependency_4.arike_pb.ListStacksResponse>, callback: grpc_1.sendUnaryData<dependency_4.arike_pb.ListStacksResponse>): void;
        abstract PutStacks(call: grpc_1.ServerUnaryCall<dependency_4.arike_pb.PutStacksRequest, dependency_4.arike_pb.PutStacksResponse>, callback: grpc_1.sendUnaryData<dependency_4.arike_pb.PutStacksResponse>): void;
        abstract PopStacks(call: grpc_1.ServerUnaryCall<dependency_4.arike_pb.PopStacksRequest, dependency_4.arike_pb.PopStacksResponse>, callback: grpc_1.sendUnaryData<dependency_4.arike_pb.PopStacksResponse>): void;
        abstract CreateFifos(call: grpc_1.ServerUnaryCall<dependency_5.arike_pb.CreateFifosRequest, dependency_5.arike_pb.CreateFifosResponse>, callback: grpc_1.sendUnaryData<dependency_5.arike_pb.CreateFifosResponse>): void;
        abstract DeleteFifos(call: grpc_1.ServerUnaryCall<dependency_5.arike_pb.DeleteFifosRequest, dependency_5.arike_pb.DeleteFifosResponse>, callback: grpc_1.sendUnaryData<dependency_5.arike_pb.DeleteFifosResponse>): void;
        abstract ListFifos(call: grpc_1.ServerUnaryCall<dependency_5.arike_pb.ListFifosRequest, dependency_5.arike_pb.ListFifosResponse>, callback: grpc_1.sendUnaryData<dependency_5.arike_pb.ListFifosResponse>): void;
        abstract PushFifos(call: grpc_1.ServerUnaryCall<dependency_5.arike_pb.PushFifosRequest, dependency_5.arike_pb.PushFifosResponse>, callback: grpc_1.sendUnaryData<dependency_5.arike_pb.PushFifosResponse>): void;
        abstract PullFifos(call: grpc_1.ServerUnaryCall<dependency_5.arike_pb.PullFifosRequest, dependency_5.arike_pb.PullFifosResponse>, callback: grpc_1.sendUnaryData<dependency_5.arike_pb.PullFifosResponse>): void;
        abstract CreateSortedLists(call: grpc_1.ServerUnaryCall<dependency_6.arike_pb.CreateSortedListsRequest, dependency_6.arike_pb.CreateSortedListsResponse>, callback: grpc_1.sendUnaryData<dependency_6.arike_pb.CreateSortedListsResponse>): void;
        abstract DeleteSortedLists(call: grpc_1.ServerUnaryCall<dependency_6.arike_pb.DeleteSortedListsRequest, dependency_6.arike_pb.DeleteSortedListsResponse>, callback: grpc_1.sendUnaryData<dependency_6.arike_pb.DeleteSortedListsResponse>): void;
        abstract ListSortedLists(call: grpc_1.ServerUnaryCall<dependency_6.arike_pb.ListSortedListsRequest, dependency_6.arike_pb.ListSortedListsResponse>, callback: grpc_1.sendUnaryData<dependency_6.arike_pb.ListSortedListsResponse>): void;
        abstract InsertSortedLists(call: grpc_1.ServerUnaryCall<dependency_6.arike_pb.InsertSortedListsRequest, dependency_6.arike_pb.InsertSortedListsResponse>, callback: grpc_1.sendUnaryData<dependency_6.arike_pb.InsertSortedListsResponse>): void;
        abstract BiggestSortedLists(call: grpc_1.ServerUnaryCall<dependency_6.arike_pb.BiggestSortedListsRequest, dependency_6.arike_pb.BiggestSortedListsResponse>, callback: grpc_1.sendUnaryData<dependency_6.arike_pb.BiggestSortedListsResponse>): void;
        abstract SmallestSortedLists(call: grpc_1.ServerUnaryCall<dependency_6.arike_pb.SmallestSortedListsRequest, dependency_6.arike_pb.SmallestSortedListsResponse>, callback: grpc_1.sendUnaryData<dependency_6.arike_pb.SmallestSortedListsResponse>): void;
        abstract Authenticate(call: grpc_1.ServerUnaryCall<dependency_1.arike_pb.AuthenticateRequest, dependency_1.arike_pb.AuthenticateResponse>, callback: grpc_1.sendUnaryData<dependency_1.arike_pb.AuthenticateResponse>): void;
    }
    export class ArikedbRPCClient extends grpc_1.makeGenericClientConstructor(UnimplementedArikedbRPCService.definition, "ArikedbRPC", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        CreateCollections: GrpcUnaryServiceInterface<dependency_2.arike_pb.CreateCollectionsRequest, dependency_2.arike_pb.CreateCollectionsResponse> = (message: dependency_2.arike_pb.CreateCollectionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.arike_pb.CreateCollectionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.arike_pb.CreateCollectionsResponse>, callback?: grpc_1.requestCallback<dependency_2.arike_pb.CreateCollectionsResponse>): grpc_1.ClientUnaryCall => {
            return super.CreateCollections(message, metadata, options, callback);
        };
        DeleteCollections: GrpcUnaryServiceInterface<dependency_2.arike_pb.DeleteCollectionsRequest, dependency_2.arike_pb.DeleteCollectionsResponse> = (message: dependency_2.arike_pb.DeleteCollectionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.arike_pb.DeleteCollectionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.arike_pb.DeleteCollectionsResponse>, callback?: grpc_1.requestCallback<dependency_2.arike_pb.DeleteCollectionsResponse>): grpc_1.ClientUnaryCall => {
            return super.DeleteCollections(message, metadata, options, callback);
        };
        ListCollections: GrpcUnaryServiceInterface<dependency_2.arike_pb.ListCollectionsRequest, dependency_2.arike_pb.ListCollectionsResponse> = (message: dependency_2.arike_pb.ListCollectionsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.arike_pb.ListCollectionsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.arike_pb.ListCollectionsResponse>, callback?: grpc_1.requestCallback<dependency_2.arike_pb.ListCollectionsResponse>): grpc_1.ClientUnaryCall => {
            return super.ListCollections(message, metadata, options, callback);
        };
        CreateVariables: GrpcUnaryServiceInterface<dependency_3.arike_pb.CreateVariablesRequest, dependency_3.arike_pb.CreateVariablesResponse> = (message: dependency_3.arike_pb.CreateVariablesRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.CreateVariablesResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.CreateVariablesResponse>, callback?: grpc_1.requestCallback<dependency_3.arike_pb.CreateVariablesResponse>): grpc_1.ClientUnaryCall => {
            return super.CreateVariables(message, metadata, options, callback);
        };
        DeleteVariables: GrpcUnaryServiceInterface<dependency_3.arike_pb.DeleteVariablesRequest, dependency_3.arike_pb.DeleteVariablesResponse> = (message: dependency_3.arike_pb.DeleteVariablesRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.DeleteVariablesResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.DeleteVariablesResponse>, callback?: grpc_1.requestCallback<dependency_3.arike_pb.DeleteVariablesResponse>): grpc_1.ClientUnaryCall => {
            return super.DeleteVariables(message, metadata, options, callback);
        };
        ListVariables: GrpcUnaryServiceInterface<dependency_3.arike_pb.ListVariablesRequest, dependency_3.arike_pb.ListVariablesResponse> = (message: dependency_3.arike_pb.ListVariablesRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.ListVariablesResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.ListVariablesResponse>, callback?: grpc_1.requestCallback<dependency_3.arike_pb.ListVariablesResponse>): grpc_1.ClientUnaryCall => {
            return super.ListVariables(message, metadata, options, callback);
        };
        SetVariables: GrpcUnaryServiceInterface<dependency_3.arike_pb.SetVariablesRequest, dependency_3.arike_pb.SetVariablesResponse> = (message: dependency_3.arike_pb.SetVariablesRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.SetVariablesResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.SetVariablesResponse>, callback?: grpc_1.requestCallback<dependency_3.arike_pb.SetVariablesResponse>): grpc_1.ClientUnaryCall => {
            return super.SetVariables(message, metadata, options, callback);
        };
        GetVariables: GrpcUnaryServiceInterface<dependency_3.arike_pb.GetVariablesRequest, dependency_3.arike_pb.GetVariablesResponse> = (message: dependency_3.arike_pb.GetVariablesRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.GetVariablesResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_3.arike_pb.GetVariablesResponse>, callback?: grpc_1.requestCallback<dependency_3.arike_pb.GetVariablesResponse>): grpc_1.ClientUnaryCall => {
            return super.GetVariables(message, metadata, options, callback);
        };
        SubscribeVariables: GrpcStreamServiceInterface<dependency_3.arike_pb.SubscribeVariablesRequest, dependency_3.arike_pb.TsVarValue> = (message: dependency_3.arike_pb.SubscribeVariablesRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<dependency_3.arike_pb.TsVarValue> => {
            return super.SubscribeVariables(message, metadata, options);
        };
        CreateStacks: GrpcUnaryServiceInterface<dependency_4.arike_pb.CreateStacksRequest, dependency_4.arike_pb.CreateStacksResponse> = (message: dependency_4.arike_pb.CreateStacksRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.CreateStacksResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.CreateStacksResponse>, callback?: grpc_1.requestCallback<dependency_4.arike_pb.CreateStacksResponse>): grpc_1.ClientUnaryCall => {
            return super.CreateStacks(message, metadata, options, callback);
        };
        DeleteStacks: GrpcUnaryServiceInterface<dependency_4.arike_pb.DeleteStacksRequest, dependency_4.arike_pb.DeleteStacksResponse> = (message: dependency_4.arike_pb.DeleteStacksRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.DeleteStacksResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.DeleteStacksResponse>, callback?: grpc_1.requestCallback<dependency_4.arike_pb.DeleteStacksResponse>): grpc_1.ClientUnaryCall => {
            return super.DeleteStacks(message, metadata, options, callback);
        };
        ListStacks: GrpcUnaryServiceInterface<dependency_4.arike_pb.ListStacksRequest, dependency_4.arike_pb.ListStacksResponse> = (message: dependency_4.arike_pb.ListStacksRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.ListStacksResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.ListStacksResponse>, callback?: grpc_1.requestCallback<dependency_4.arike_pb.ListStacksResponse>): grpc_1.ClientUnaryCall => {
            return super.ListStacks(message, metadata, options, callback);
        };
        PutStacks: GrpcUnaryServiceInterface<dependency_4.arike_pb.PutStacksRequest, dependency_4.arike_pb.PutStacksResponse> = (message: dependency_4.arike_pb.PutStacksRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.PutStacksResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.PutStacksResponse>, callback?: grpc_1.requestCallback<dependency_4.arike_pb.PutStacksResponse>): grpc_1.ClientUnaryCall => {
            return super.PutStacks(message, metadata, options, callback);
        };
        PopStacks: GrpcUnaryServiceInterface<dependency_4.arike_pb.PopStacksRequest, dependency_4.arike_pb.PopStacksResponse> = (message: dependency_4.arike_pb.PopStacksRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.PopStacksResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.arike_pb.PopStacksResponse>, callback?: grpc_1.requestCallback<dependency_4.arike_pb.PopStacksResponse>): grpc_1.ClientUnaryCall => {
            return super.PopStacks(message, metadata, options, callback);
        };
        CreateFifos: GrpcUnaryServiceInterface<dependency_5.arike_pb.CreateFifosRequest, dependency_5.arike_pb.CreateFifosResponse> = (message: dependency_5.arike_pb.CreateFifosRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.CreateFifosResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.CreateFifosResponse>, callback?: grpc_1.requestCallback<dependency_5.arike_pb.CreateFifosResponse>): grpc_1.ClientUnaryCall => {
            return super.CreateFifos(message, metadata, options, callback);
        };
        DeleteFifos: GrpcUnaryServiceInterface<dependency_5.arike_pb.DeleteFifosRequest, dependency_5.arike_pb.DeleteFifosResponse> = (message: dependency_5.arike_pb.DeleteFifosRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.DeleteFifosResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.DeleteFifosResponse>, callback?: grpc_1.requestCallback<dependency_5.arike_pb.DeleteFifosResponse>): grpc_1.ClientUnaryCall => {
            return super.DeleteFifos(message, metadata, options, callback);
        };
        ListFifos: GrpcUnaryServiceInterface<dependency_5.arike_pb.ListFifosRequest, dependency_5.arike_pb.ListFifosResponse> = (message: dependency_5.arike_pb.ListFifosRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.ListFifosResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.ListFifosResponse>, callback?: grpc_1.requestCallback<dependency_5.arike_pb.ListFifosResponse>): grpc_1.ClientUnaryCall => {
            return super.ListFifos(message, metadata, options, callback);
        };
        PushFifos: GrpcUnaryServiceInterface<dependency_5.arike_pb.PushFifosRequest, dependency_5.arike_pb.PushFifosResponse> = (message: dependency_5.arike_pb.PushFifosRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.PushFifosResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.PushFifosResponse>, callback?: grpc_1.requestCallback<dependency_5.arike_pb.PushFifosResponse>): grpc_1.ClientUnaryCall => {
            return super.PushFifos(message, metadata, options, callback);
        };
        PullFifos: GrpcUnaryServiceInterface<dependency_5.arike_pb.PullFifosRequest, dependency_5.arike_pb.PullFifosResponse> = (message: dependency_5.arike_pb.PullFifosRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.PullFifosResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_5.arike_pb.PullFifosResponse>, callback?: grpc_1.requestCallback<dependency_5.arike_pb.PullFifosResponse>): grpc_1.ClientUnaryCall => {
            return super.PullFifos(message, metadata, options, callback);
        };
        CreateSortedLists: GrpcUnaryServiceInterface<dependency_6.arike_pb.CreateSortedListsRequest, dependency_6.arike_pb.CreateSortedListsResponse> = (message: dependency_6.arike_pb.CreateSortedListsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.CreateSortedListsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.CreateSortedListsResponse>, callback?: grpc_1.requestCallback<dependency_6.arike_pb.CreateSortedListsResponse>): grpc_1.ClientUnaryCall => {
            return super.CreateSortedLists(message, metadata, options, callback);
        };
        DeleteSortedLists: GrpcUnaryServiceInterface<dependency_6.arike_pb.DeleteSortedListsRequest, dependency_6.arike_pb.DeleteSortedListsResponse> = (message: dependency_6.arike_pb.DeleteSortedListsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.DeleteSortedListsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.DeleteSortedListsResponse>, callback?: grpc_1.requestCallback<dependency_6.arike_pb.DeleteSortedListsResponse>): grpc_1.ClientUnaryCall => {
            return super.DeleteSortedLists(message, metadata, options, callback);
        };
        ListSortedLists: GrpcUnaryServiceInterface<dependency_6.arike_pb.ListSortedListsRequest, dependency_6.arike_pb.ListSortedListsResponse> = (message: dependency_6.arike_pb.ListSortedListsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.ListSortedListsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.ListSortedListsResponse>, callback?: grpc_1.requestCallback<dependency_6.arike_pb.ListSortedListsResponse>): grpc_1.ClientUnaryCall => {
            return super.ListSortedLists(message, metadata, options, callback);
        };
        InsertSortedLists: GrpcUnaryServiceInterface<dependency_6.arike_pb.InsertSortedListsRequest, dependency_6.arike_pb.InsertSortedListsResponse> = (message: dependency_6.arike_pb.InsertSortedListsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.InsertSortedListsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.InsertSortedListsResponse>, callback?: grpc_1.requestCallback<dependency_6.arike_pb.InsertSortedListsResponse>): grpc_1.ClientUnaryCall => {
            return super.InsertSortedLists(message, metadata, options, callback);
        };
        BiggestSortedLists: GrpcUnaryServiceInterface<dependency_6.arike_pb.BiggestSortedListsRequest, dependency_6.arike_pb.BiggestSortedListsResponse> = (message: dependency_6.arike_pb.BiggestSortedListsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.BiggestSortedListsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.BiggestSortedListsResponse>, callback?: grpc_1.requestCallback<dependency_6.arike_pb.BiggestSortedListsResponse>): grpc_1.ClientUnaryCall => {
            return super.BiggestSortedLists(message, metadata, options, callback);
        };
        SmallestSortedLists: GrpcUnaryServiceInterface<dependency_6.arike_pb.SmallestSortedListsRequest, dependency_6.arike_pb.SmallestSortedListsResponse> = (message: dependency_6.arike_pb.SmallestSortedListsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.SmallestSortedListsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_6.arike_pb.SmallestSortedListsResponse>, callback?: grpc_1.requestCallback<dependency_6.arike_pb.SmallestSortedListsResponse>): grpc_1.ClientUnaryCall => {
            return super.SmallestSortedLists(message, metadata, options, callback);
        };
        Authenticate: GrpcUnaryServiceInterface<dependency_1.arike_pb.AuthenticateRequest, dependency_1.arike_pb.AuthenticateResponse> = (message: dependency_1.arike_pb.AuthenticateRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.arike_pb.AuthenticateResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.arike_pb.AuthenticateResponse>, callback?: grpc_1.requestCallback<dependency_1.arike_pb.AuthenticateResponse>): grpc_1.ClientUnaryCall => {
            return super.Authenticate(message, metadata, options, callback);
        };
    }
}
